title: ZJUTHESIS
description: Zhejiang University Graduation Thesis LaTeX template
theme: jekyll-theme-slate
show_downloads: false
github:
  zip_url: https://github.com/TheNetAdmin/zjuthesis/releases/latest
  tar_url: https://github.com/TheNetAdmin/zjuthesis/releases/latest
